spring.application.name=mgmt
spring:
    datasource:
        url: jdbc:mariadb://localhost:3306/test
        username: hey880
        password: lee880!
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
